---
- name: Download and install maven on ubuntu
  hosts: webservers
  become: yes
  tasks:
    - name: Install java
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes

    - name: Download maven from apache website
      get_url:
        url: https://dlcdn.apache.org/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.tar.gz
        dest: /opt
        mode: '0775'

    - name: Extract maven tar file
      unarchive:
        src: /opt/apache-maven-3.9.4-bin.tar.gz
        dest: /opt
        remote_src: yes

    - name: Removing maven tart file
      file:
        path: /opt/apache-maven-3.9.4-bin.tar.gz
        state: absent
    
    - name: Renaming a file
      command: mv /opt/apache-maven-3.9.4 /opt/maven

    - name: set environment variable
      lineinfile: dest=/root/.bashrc line='export PATH=$PATH:/opt/maven/bin' insertafter='EOF' regexp='export PATH=\$PATH:/opt/maven/bin' state=present
